apiVersion: v1
kind: Service
metadata:
  # TODO: it would be cleaner to derive service name from deployment name in values.yaml, then reference service name here, but this is fine.
  name: {{ .Values.deployment.fullname }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPortName }}
      protocol: {{ .Values.service.protocol }}
      #name: http  # TODO: can generalize this to use named port instead of literal port from values? recall that named ports are required in some cases
  selector:
    {{- with .Values.deployment.selectorLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
